use_frameworks!

platform :ios, '9.0'

target 'SKDebugSuite_Example' do
  pod 'SKDebugSuite', :path => '../'

  target 'SKDebugSuite_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
